server:
  port: 8080
    
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.15:5432/rms_miniapp
    username: postgres
    password: postgres
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redis
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    user:
      name: admin
      password: admin
  mvc:
    favicon:
      enabled: false
management:
  endpoint:
    health:
      enabled: true
  server:
    port: 54001

